### ISSUE TITLE
Runtime error on missing AsyncParser$Mode

### ISSUE THREAD

**Issue by jrgonzalezg** [circe/circe-iteratee#10]
I am getting a runtime error when trying to parse a file using `byteStreamParser`. The error I am getting is:
```
A needed class was not found. This could be due to an error in your runpath. Missing class: jawn/AsyncParser$Mode
java.lang.NoClassDefFoundError: jawn/AsyncParser$Mode
```

I have researched it a bit and the jawn library declares that file on package `org.typelevel.jawn` while circe-iteratee imports it as `_root_.jawn.AsyncParser` which seems to be missing the `org.typelevel` part which could explain the issue. But I tried to modify the code to submit a PR and circe iteratee does not work if I change the import. In other words, my project does not find that class as `import _root_.jawn.AsyncParser` and circe-iteratee seems to not recognize it as either
 `import _root_.org.typelevel.jawn.AsyncParser` or just `import org.typelevel.jawn.AsyncParser`. How is the package changed / remapped on circe-iteratee? And why it does not work with the package that jawn itself uses (org.typelevel.jawn)?

**Comment by travisbrown** [comment]
Sorry to have missed this issue, but the issue should be resolved with the 0.12.0 release of this project, assuming you're using circe 0.11.x and Jawn 0.14.x.
